project:
  type: book

book:
  favicon: logo.png
  title: "The Book of Knowledge"
  author: "Dr. Kai Aragaki, Bridget McGuire, Dr. Elina Vlachou, Gabriela Colocho"
  date: "2025-03-13"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Protocols"
      chapters:
        - diluting-things.qmd
        - cell-culture.qmd
        - three-d-cell-culture.qmd
        - cell-modification.qmd
        - cell-line-extraction-methods.qmd
        - ffpe-extraction-methods.qmd
        - lib-prep.qmd
        - western-blot.qmd
        - dd-ct-pcr.qmd
        - mtt.qmd
        - transwells.qmd
        - qc.qmd
        - Urine_Protocols.qmd
    - part: analysis.qmd
      chapters:
        - analysis_setup.qmd
        - qpcr_analysis.qmd
        - mtt_analysis.qmd

format:
  html:
    theme:
      - litera
      - custom.scss
    filters:
      - custom-callout.lua
