project:
  type: book

book:
  title: "The Book of Knowledge"
  author: "Kai Aragaki, Bridget McGuire"
  date: "2022-01-06"
  chapters:
    - index.qmd
    - intro.qmd
    - part: "Protocols"
      chapters:
        - cell-culture.qmd
        - three-d-cell-culture.qmd
        - cell-modification.qmd
        - cell-line-extraction-methods.qmd
        - ffpe-extraction-methods.qmd
        - western-blot.qmd
        - dd-ct-pcr.qmd
        - mtt.qmd

format:
  html:
    theme: litera



