---
fig-cap-location: margin
reference-location: margin
---


# Cell Line Extraction Methods

## RNA (TRIzol)
[The following method is adapted from the Invitrogen TRIzol reagent user guide]{.aside}

:::{.callout-prep}
**Required materials:**

   - TRIzol
   - Chloroform
   - RNase-free glycogen
   - Isopropanol
   - Freshly prepared 75% ethanol
   
**Before you begin:**

   - Get ice
   - Set a heatblock to $60^\circ C$
:::

### Lysis and Phase Separation

Lyse and homogenize samples in TRIzol Reagent according to your starting material: 

#### Tissues
1. Add $1mL$ of TRIzol Reagent per $50–100mg$ of tissue to the sample and homogenize using a homogenizer

#### Cell grown in monolayer

##### Trypsinizing
If you are planning to measure %GFP+ or you are isolating cells from only one well of a multi-well plate e.g. during a time course experiment:

1. In the hood, trypsinize the cells and transfer them to a 15mL conical
   - For a 6 well plate, trypsinize with $0.5mL$ trypsin and quench with $1mL$ medium.
   - At this point, you can measure %GFP+, for instance.
2. Centrifuge at $300\times g$ for $5\ minutes$
3. Aspirate the supernatant
4. Add $300\mu L$ TRIzol to the tube and transfer to a 1.5mL microfuge tube

##### Direct Lysis
1. Aspirate the medium
2. Add $0.3–0.4 mL$ of TRIzol Reagent per $1 \times 10^5—1 \times 10^7$ cells directly to the culture dish to lyse the cells
3. Use a cell scraper to scrape the cells off the plate
4. Transfer the lysate to a 1.5mL microfuge tube

#### Cells grown in suspension: 
1. Pellet the cells by centrifugation and discard the supernatant. 
2. Add $0.75 mL$ of TRIzol Reagent per $0.25 mL$ of sample ($5–10 \times 10^6$ cells from animal, plant, or yeast origin or $1 \times 10^7$ cells of bacterial origin) to the pellet.
3. Pipet the lysate up and down several times to homogenize

:::{.callout-note}
The sample volume should not exceed 10% of the volume of TRIzol Reagent used for lysis. 
:::

:::{.callout-note}
Samples can be stored at $4^\circ C$ overnight or at $–20^\circ C$ for up to a year. 
:::

:::{.callout-note}
If samples have a high fat content, centrifuge the lysate for $5\ minutes$ at $12,000 \times g$ at $4^\circ C$, then transfer the clear supernatant to a new tube
:::

#### Lysis and Phase Separation Cont.
1. Vortex for $10\ seconds$
2. Incubate for $5\ minutes$ to permit complete dissociation of the nucleoproteins complex
3. **In the fume hood**, add $0.2\ mL$ of chloroform **per 1 mL of TRIzol Reagent** used for lysis, then securely cap the tube
   - For $300\mu L$ TRIzol, add $60\mu L$ chloroform 
4. Mix by shaking, for about $30\ seconds$
   - This is best done putting the tubes on one rack, then sandwiching another rack atop the lids. Grab the whole sandwich and shake it.
5. Incubate for $3\ minutes$
6. Centrifuge samples for $15\ minutes$ at $12,000\times g$ at $4^\circ C$. The mixture separates into a lower red phenol-chloroform, and interphase, and a colorless upper aqueous phase
7. Transfer the aqueous phase containing the RNA to a new tube by angling the tube at 45° and pipetting the solution out
   - For a 6-well with $300 \mu L$ of TRIzol used, $200\mu L$ tends to be the right amount to take
   - Avoid transferring any of the interphase or organic layer when removing the aqueous phase.

#### Isolate RNA
    
##### Precipitate the RNA

1. (Optional but HIGHLY RECOMMENDED) Add $10\mu g$ of RNase-free glycogen as a carrier to the aqueous phase
2. Add $0.5mL$ of isopropanol to the aqueous phase per $1mL$ of TRIzol used for lysis
   - For $300\mu L$ TRIzol, add $150\mu L$ isopropanol
2. Vortex for a few seconds until mixed.
3. Incubate for $10\ minutes$
4. Centrifuge for $10\ minutes$ at $12,000\times g$ at $4^\circ C$ 
   - Total RNA precipitate forms a white gel-like pellet at the bottom of the tube. 
5. Aspirate the supernatant
   - It is helpful to take most of the volume out with a P1000, then remove the liquid closer to the pellet with a P200

#### Wash the RNA

1. Resuspend the pellet in 1mL of 75% ethanol per 1 mL of TRIzol Reagent used for lysis. 
   - For $300\mu L$ TRIzol, add $300\mu L$ 75% ethanol
   - Note: The RNA can be stored in 75% ethanol for at least 1 year at $–20^{\circ}C$, or at least 1 week at $4^{\circ}C$
2. Vortex briefly
3. Centrifuge for $5\ minutes$ at $7500\times g$ at $4^\circ C$
4. Aspirate the supernatant
   - It is helpful to take most of the volume out with a P1000, then remove the liquid closer to the pellet with a P200
   - You can speed up the drying time, and increase your 260/230 metrics, by *gently* flicking the pellet to dislodge the liquid from it, then using a P20 or aspirator to remove the dispersed droplets not containing the pellet.
5. Let the pellet air dry, just before the pellet turns clear.
   - If the pellet overdries, it may not solubilize and may have a low A260/A280.
6. Add $20-50 \mu L$ of RNAse-free water to each pellet 
7. Incubate at $60^{\circ}C$ for $10\ minutes$
8. Store the RNA at $–80^{\circ}C$.


## RNA (mirVana)
[The following method is adapted from the mirVana miRNA Isolation Kit protocol]{.aside}

This kit is much more expensive per sample than TRIzol, but tends to produce purer results. It's typically only necessary for higher-stakes experiments like sequencing, but not for qPCR.

:::{.callout-prep}
The night before, plate cells in a 6 well plate. 200K cells/mL is a good number.

**Before you begin:**

* Get a bucket of ice
* Set the heatblock to $95^\circ C$ and add a microfuge tube with nuclease free H2O. You will need at least 50uL per sample - be generous with this!
* For each sample, label 4 tubes - two standard 1.5mL microfuge tubes, two collection tubes
:::


### Lysing Cells

1. Take 6 well plate from incubator. 
2. Aspirate off medium, then gently add $2mL$ PBS/well.
3. Aspirate off PBS, then add $300\mu L$ lysis buffer/well
4. Incubate at RT for $3\ minutes$
5. Use a cell scraper^[Cat# 83.3950] to scrape cells from the bottom of the well
* Don't forget to get all the edges
* Try not to let the scraper skip
* After scraping the bottom of the well, tilt the plate and sweep the lysate to the bottom to allow for easy transfer.
* Use a new scraper for each well
6. Transfer lysate to regular 1.5mL microfuge tube
7. Put on ice


### Organic Extraction

1. Add $\frac{1}{10}vol$^[A 'volume' refers to the pre-miRNA-Homogenate-Additive volume. If you follow this protocol, $\frac{1}{10}vol$ is $30 \mu L$] miRNA Homogenate Additive
2. Vortex $15\ seconds$
3. Put on ice for $10\ minutes$
4. Add $1\ vol$ phenol:chloroform

:::{.callout-warning}
Perform addition of phenol:chloroform and transfer of upper phase to a new tube under the fume hood - phenol:chloroform vapors are toxic.
:::

5. Vortex for $45\ seconds$
6. Centrifuge at $max\ speed$ for $5\ minutes$
7. Put phenol:chloroform away
8. Remove upper phase, transfer to fresh 1.5mL microfuge tube

:::{.callout-warning}
Err on the side of caution to avoid disturbing lower phase. As a rule of thumb, if you add 300uL lysis buffer, remove ~200uL. Your mileage may vary.

Make sure to note the volume of upper phase removed.
:::


### Total RNA Isolation

1. Add $1.25\ vol$ 100% EtOH
2. Vortex $15\ seconds$
3. Spin^[Henceforth for this protocol, 'spin' = $30\ seconds$ at $10000 \times g$] up to $600\mu L$ sample through filter cartridge into collection tube
4. Aspirate flow through
5. Add $600 \mu L$ Wash Solution 1, spin, and aspirate
6. Add $500 \mu L$ Wash Solution 2/3, spin, and aspirate
7. Add $500 \mu L$ Wash Solution 2/3, spin, aspirate, and spin for $1\ minute$
8. Transfer filter to fresh collection tube
9. Add $50 \mu L$ $95^\circ C$ H2O, spin
10. Measure concentration, 260/280, and 260/230 via NanoDrop

### TURBO DNA-free Treatment

[Adapted from Cat# AM1907 publication 1907M, revision H]{.aside}

:::{.callout-prep}
**Before you begin:**

- Remove reagents from refrigerator, leave on ice. 
- Turn heat block to $37^\circ C$ 
- Label one set of 1.5mL microfuge tubes, another set of 0.5mL microfuge tubes. 
- If you have many samples, a 96 well plate (with V bottoms) may be a better idea. 
- You should still prepare a set of labelled tubes for storage 
- If RNA concentration $>200ng/\mu L$, dilute to $200ng/\mu L$
:::

:::{.callout-tip}
Anywhere between $10-100\mu L$ sample is typical, with $50\mu L$ being typical
:::

1. Add $0.1\ volume$ of 10X TURBO DNase Buffer to RNA
2. Add $1\mu L$ TURBO DNase to RNA
3. Mix gently
4. Incubate at $37^\circ C$ for $30\ minutes$
5. Vortex DNase Inactivation Reagent to resuspend, then add $0.1\ volume$ (minimum $2\mu L$)

:::{.callout-tip}
If the reagent is dried up and can't be pipetted, determine how much volume of reagent there is, then add 25% of that volume of nuclease-free water.
:::

6. Incubate at $RT$ for $5\ minutes$, flicking every $1.5\ minutes$
7. Centrifuge at $10,000 \times g$ for $1.5\ minutes$ for 1.5mL tubes, or $2000 \times g$ for $5\ minutes$ for 96-well plates. 
8. Transfer supernatant to labelled tube for storage. Store at $\le -20^\circ C$

:::{.callout-warning}
Ensure you do not get any of the pellet.
:::

## DNA

[The following method is adapted from a modified version of the DNeasy Blood & Tissue Kit (April 2016) protocol, and assumes you are using cell lines.]{.aside}

1. Centrifuge $\le 5\times10^6$ cells for $5\ minutes$ at $300 \times g$
2. Remove supernatant
3. Add $200\mu L$ PBS
4. Add $20\mu L$ proteinase K
5. Add $20\mu L$ 5mg/mL RNAse A. Incubate for $5\ minutes$ at RT.
6. Add $200\mu L$ Buffer AL
7. Add $200\mu L$ 100% ethanol. Vortex thoroughly.
8. Transfer solution to DNeasy Mini spin column place in a 2mL collection tube.
9. Spin for $1\ minute$ at $\ge 6000 \times g$
10. Discard collection tube and replace with a fresh one.
11. Add $500\mu L$ Buffer AW1
12. Spin for $1\ minute$ at $\ge 6000 \times g$
13. Discard collection tube and replace with a fresh one.
14. Add $500\mu L$ Buffer AW2
15. Spin for $3\ minutes$ at $20000 \times g$
16. Discard collection tube and replace with a permanent collection tube.
17. Add $40\mu L$ nuclease-free H2O
18. Incubate for $1\ minute$
19. Spin for $1\ minute$ at $\ge6000 \times g$


## Protein

See [Obtaining Protein Lysates](#sec-obtaining-protein-lysates)

## Histones
[Adapted from ab113476]{.aside}

::: callout-prep
Get ice
:::

### Reagent Preparation

::: callout-note
Briefly centrifuge small vials at low speed prior to opening. Prepare fresh reagents immediately prior to use. 
:::

#### 1X Pre-Lysis Buffer
1. Dilute $1mL$ of **10X Pre-Lysis Buffer** with $9mL$ nano-pure water

#### Balance-DTT Buffer
1. Add $1μL$ of **DTT Solution** to $500μL$ of **Balance Buffer**

### Sample Preparation 

#### Tissues (treated or untreated)
1. Weigh the sample and record its mass
2. Cut the sample into small pieces (1-2 mm³) with a scalpel or scissors.
3. Transfer the tissue pieces to a Dounce homogenizer.
4. Add $5μL/mg\ tissue$ of **1X Pre-Lysis buffer** to homogenizer
5. Disaggregate tissue pieces by 50-60 strokes 
6. If total mixture volume is less than 1mL, transfer mixture to a 1.5mL microfuge tube and centrifuge at $10,000×g$ for $1\ minute$ at $4°C$. Otherwise, transfer homogenized mixture to a 15 mL conical tube and centrifuge at $2000×g$ for $5\ min$ at $4°C$. 
7. Remove supernatant.
 
#### Cells (treated or untreated)
1. Harvest and pellet the cells by centrifugation at $200×g$ for $5\ minutes$ at $4°C$ 
2. Re-suspend cells in the **1X Pre-Lysis Buffer** at $10^7\ cells/mL$
3. Lyse cells on ice for $10\ minutes$ with gentle stirring. 
4. If lysates were prepared in a 1.5mL microfuge tube, centrifuge at $10,000×g$ for $1\ minute$ at $4°C$. If prepared in a 15mL conical, centrifuge at $2000×g$ for $5\ minutes$ at $4°C$. 
5. Remove supernatant.

### Extraction Protocol
1. Re-suspend pellet in **3 volumes** (approximately 200 µL/10^7 cells or 100 mg of tissue) of **Lysis Buffer**. If not in a 1.5mL tube, transfer it to one.
2. Incubate on ice for $30\ minutes$
3. Centrifuge at $15,000×g$ for $5\ minutes$ at $4°C$
4. Transfer the supernatant fraction (containing acid-soluble proteins) to a fresh 1.5mL microfuge tube
5. Immediately add $0.3\ volumes$ of the **Balance-DTT Buffer** to the supernatant (e.g., 0.3 mL of Balance-DTT Buffer to 1 ml of supernatant). 
6. Store the extract at $-20°C$ for several days, or $-80°C$ for long-term storage. Avoid repeated thawing and freezing. 

### PROTOCOL QUESTIONS:
1. What does it mean to be treated or untreated?
2. Is the change in rpm due to an assumed decrease in rotor arm length?
3. I've modified it such that the volume is less than 1mL, since we don't usually have 2mL vials
4. Protocol said to do 12000 rpm but did never said to transfer it to a smaller tube if it was in a big one...leading me to believe they wanted me to spin something down at 12000 rpm in my big beckman coulter?
5. Removed the quantify part. This doesn't seem necessary
6. Had transfer in step 4 of extraction protocol be to a 1.5mL microfuge tube. Is this what you do?
7. Is the amount of reagent you prepare enough? How do you know how much to prepare ahead of time?
