---
title: "Diluting things"
execute: 
  echo: FALSE
---

Very little math knowledge is needed to get by in the lab. However, the math that is needed is used frequently: the calculation to dilute a substance from a higher concentration to a lower concentration. This work is really driven only by a single equation:

$$
C_1\times V_1  = C_2 \times V_2
$$

## Diluting Liquids

Suppose you have a drug that you know has a concentration of $1\mu M$, and you want to perform an experiment with it. The questions you have to ask yourself first are:

1.  What concentration do I **want** the drug to be?
2.  How much volume of diluted drug to I need?

Suppose you ask yourself this and decide you need $10mL$ of $10nM$ drug.

Now we apply our equation - but first, let's describe what the variables mean.

-   $C_1$: The concentration you start with. For us, this is $1\mu M$
-   $V_1$: The volume of the stock you will dilute with medium to get the final volume. We don't know this.
-   $C_2$: The concentration you want. This is $10nM$.
-   $V_2$: The volume you want. This is $10mL$

If you rearrange the equation, you can get:

$$
V_1 = \frac{C_2\times V_2}{C_1}
$$

Which we substitute in our known values for:

$$
V_1 = \frac{10nM\times 10mL}{10\mu M}
$$

Now we need to convert units - I find it's (generally) easier to convert to a smaller unit than vice-versa - do what ever works best for you, just don't make a mistake!

$$
V_1 = \frac{10nM\times 10mL}{10,000nM} = \frac{1mL}{100} = 0.01mL = 10\mu L
$$

Ok, our answer is $10\mu L$. But what does this mean?

This is the amount of stock ($10\mu M$) drug we are going to *dilute to* $10mL$. Note that I did *not* say we would *add to* $10mL$. While this would work (and this is in fact what we do in this case), the wording matters if, say, we wanted to dilute from $10\mu M$ to $5 \mu M$ with a final volume of $5mL$:

$$
V_1 = \frac{5\mu M\times 10mL}{10\mu M} = 5mL
$$

If we took our $5mL$ of stock and *added to* $10mL$, we would have a final volume of $15mL$. Instead of having a final concentration of $5\mu M$, we would have a final concentration of $\sim 3.3 \mu M$. And woe to thee who is using this method to do a serial dilution, where the error will multiply!

So, back to our problem. We are going to dilute $10\mu L$ of our stock *to* $10mL$. We *theoretically* should dilute in $9.99mL$ of whatever we're diluting with. However, the difference is negligable. In fact, we can use our equation in another way to see just how little it matters:

$$
C_2 = \frac{C_1\times V_1}{V_2} 
= \frac{10\mu M \times 10\mu L}{10.01mL} 
= \frac{10\mu M \times 10\mu L}{10010\mu L}
= 9.99001nM
$$

To put that in perspective, you would get the same error if you pipetted $9.99\mu L$ vs $10\mu L$ of stock into your solution - a much more likely error!

So when SHOULD you care?

Generally, I typically care when the volume is $\ge 1\%$ of my final volume.

### Serial Dilutions

Suppose instead of in our previous example where we started with a $10 \mu L$ stock, we instead started with a $10mM$ stock. Then, when we do our calculation, we get:

$$
V_1 = \frac{10nM\times 10mL}{10,000,000nM} = \frac{1mL}{100,000} = 0.00001mL = 0.01\mu L
$$

There's simply no way that you'd be able to pipette $<1\mu L$ - so we need to create an intermediate dilution. By looking at our final volume, we realize that this intermediate dilution must be at least $100\times$ more dilute than the current stock. (because $100\times 0.01\mu L = 1\mu L$, and $1\mu L$ is the lowest we can pipette). To make this intermediate dilution, we again need to ask ourselves the two questions above:

1.  What concentration do I **want** the drug to be? (100x more dilute than stock - so $100\mu M$, for example)
2.  How much volume of diluted drug to I need? (Enough to be able to make accurately and enough to use for our next (final) dilution - so $\ge 100\mu L$ so that $V_1 \ge 1\mu L$)

Unless there isn't a lot of drug to go around, I usually just make $V_2 = 1mL$. So to make a $1:100$ dilution, I would add $10\mu L$ $10mM$ drug to $990\mu L$ medium (if medium is the correct diluent). Then, vortex the sample - you can now start your calculation with a $100\mu M$ stock instead of a $10mM$ stock

## Diluting Solids

::: Helpful-note
\> One mole is the molar weight in grams of a given molecule

\> The solubility can be looked up on Selleck
:::
