---
fig-cap-location: margin
reference-location: margin
---

# Transwell Assays

:::{.callout-tip}
'Traditional', gentian-violet staining transwell assays have been superseded by a more rapid DAPI staining protocol
:::

## Plating

:::{.callout-note}
If performing a matrigel invasion assay, remove transwell chambers from $-20^\circ C$ and allow to reach room temperature ($20min$)

Incubate invasion chambers at $37^\circ C$, $2hr$, 5% CO2, in room temperature SFM. Add $750\mu L$ to bottom chamber and $500\mu L$ to upper chamber.
:::

:::{.callout-note}
Warm PBS, Medium, SFM, FBS, and trypsin

Prepare 30% FBS medium. At minimum, 750uL will be needed per well.
:::

1. Aspirate medium off cells
2. Rinse with an [appropriate volume of PBS](#gen-notes)
3. Aspirate off PBS
4. Rinse again with PBS
5. Aspirate off PBS
6. Add an [appropriate volume of trypsin](#gen-notes)
7. Place in incubator

:::{.callout-warning}
Check cells every minute, being careful not to over-trypsinize. Over trypsinization can cause changes in motility due to destruction of cell-surface constructs.

Gently tap the flask against the edge of a counter to dislodge loose cells. Stop once cells have been ~80% trypsinized.
:::

8. Once cells have been trypsinized, add medium to neutralize trypsin
9. Spin for $5min$ at $300g$
10. Aspirate supernatant
11. Resuspend in $10mL$ PBS
12. Spin for $5min$ at $300g$
13. Aspirate supernatant.
14. Resuspend in $1mL$ SFM.
15. [Determine cell concentration](#count-cells)
16. Dilute cells with SFM to achieve desired concentration

:::{.callout-tip}
For a Matrigel assay, we typically concentrate cells at 30K/well, or 60K/mL
:::

17. Remove invasion chambers from incubator. Move transwell inserts to free wells. Aspirate off medium in lower chamber

:::{.callout-warning}
Ensure you don't touch the tip of the aspirator to the membrane itself - it may damage the filter and cause aberrations in migration.
:::

18. Add $750\mu L$ 30% FBS medium to the lower chambers
19. Aspirate medium from upper chamber, add $500\mu L$ cells, and transfer insert to a chamber with 30% FBS medium

:::{.callout-warning}
Ensure there are no bubbles on the bottom of the insert. If there are, gently lift and tilt the insert around until it goes away. It's more of a 'do it until it works' rather than an actual technique
:::

20. Incubate for desired period of time. 

:::{.callout-tip}
Generally for Matrigel invasion assays this is 20hrs. For migration (uncoated transwell) assays, this can be anywhere from 4 to 20hrs (someimes beyond)
:::

## Processing

:::{.callout-note}
Make sure there's enough ($\sim 750\mu L/well$) methanol in the $-20^\circ C$ freezer (CS3, door - probably). If not, pour some more in and wait for it to cool.

You'll need at least one 24 well 'receiving plate' that you'll be soaking the transwell inserts in various reagents in. If you are doing 1-2 conditions (3-6 inserts) you will need 1 plate; 3 conditions will need 2 plates; 4-6 conditions is least confusing with 3 plates.
:::

1. Take plate from incubator
2. Add $750\mu L$ $-20^\circ C$ methanol to as many wells as there are transwell inserts to the a receiving plate
3. Pick up a transwell with tweezers and aspirate the medium from the inside
4. Aspirate medium from the bottom of the insert by tilting the insert to the side and gently touching the aspirator against edge of the filter

:::{.callout-warning}
Don't touch the aspirator to the filter itself - the suction is powerful enough to not require contact.
:::

5. Place the insert in methanol. Repeat for all remaining transwells. Wait $10min$.

:::{.callout-note}
While waiting, ensure that you have a 50mL conical of PBS. Since you'll be dipping cotton swabs into it, I label this as 'cotton swab PBS' to make sure I don't use it for anything else.

While waiting, add $750\mu L$ PBS to enough wells to accomodate the inserts
:::

6. Pick up an insert with tweezers and remove methanol by taking a dry cotton swab and touching it lightly to the inside and outside bottom edge (similar to the aspiration in step 4)
7. Place the insert in a free well. Hold the insert firmly with the tweezers in one hand. With the other hand, dip a cotton swab in the cotton swab PBS, then rub the bottom inside of the transwell. Ensure you get the corners.

:::{.callout-tip}
I do this 10 times with one cotton swab tip, then 10 times with a different cotton swab tip

You can be fairly firm with these transwell inserts, but not much pressure is needed.
:::

8. Place the insert in the PBS. Repeat for all remaining transwells. Wait $10min$

:::{.callout-note}
While waiting, take an aliquot ($11\mu L$) of DAPI from the freezer (CS3, door) and place it in a dark environment (either a drawer or pocket is fine)

While waiting, combine $9.9mL$ PBS with $100\mu L$ Triton-X 100 and vortex very well. Add $10\mu L$ of DAPI to the mixture, then vortex well. Store in a dark place.
:::

9. Add $750\mu L$ DAPI mixture to a well for each insert.
10. Pick up a transwell and wick away the PBS from the inside and outside edge of the insert
11. Place insert in DAPI mixture. Repeat for all remaining transwells. Place plate in a dark place. Wait $10min$.
12. Wick away DAPI mixture as in step 10. Transfer back to PBS wells. Wait $10min$

:::{.callout-note}
While waiting, take a new 96 well plate and for each insert add $1mL$ diH2O to each well
:::

13. Wick away PBS and transfer each insert to the diH2O wells.
14. Add $750\mu L$ diH2O to the inside of every insert


## Imaging

1. Image on EVOS using DAPI filter and the 4x objective

2. Save as .tif. Do not save with image annotation.


:::{.callout-tip}
In later steps, you'll be analyzing these images using a custom cell profiler pipeline. To minimize the amount of customization that you'll need to do, I'd recommend saving your files in this format:

```
YYYY-MM-DD_cell-line_transwell-type
|---> drug-condition-1
      |---> rep-1.tif
      |---> rep-2.tif
      |---> rep-3.tif
|---> drug-condition-2
      |---> rep-1.tif
      |---> rep-2.tif
      |---> rep-3.tif
...
```

For example, say that I performed transwells with three different conditions: UC6 cells with matrigel transwells with DMSO or mydruginib, and SCaBER cells with uncoated transwells, no drug. My files would look like:

```
2021-04-21_uc6_mat
|---> dmso
      |---> 1.tif
      |---> 2.tif
      |---> 3.tif
|---> mydruginib
      |---> 1.tif
      |---> 2.tif
      |---> 3.tif
2021-04-21_scaber_unc
|---> none
      |---> 1.tif
      |---> 2.tif
      |---> 3.tif
```

:::


## Quantifying

1. Download [CellProfiler](https://cellprofiler.org/)
2. Download this pipeline
3. Point CellProfiler to the folder containing all your unanalyzed transwell experiments (the top level of the file system shown in the tip box above)
4. Run test mode with a few images to ensure the parameters are accurately capturing the cells.

:::{.callout-tip}
If cells aren't being counted properly, there are a couple things you can do: 

* Change the size required to be considered
* Change the luminance required to be considered

This generally takes some trial and error.

Sometimes, some parameters will only work for a given condition, or even a given image, but not others. In this instance, I make a note of it, and I run with the parameters that seem to work for the most images. Then, I remove the images for which it worked from the file list, tweak the parameters, and repeat until there are no files left.
:::

5. The counts of cells are stored in a file labeled `counts_image.txt`, which can be found in a directory with a name with the format of `YYYY-MM-DD_cell-line_transwell-type_drug`. The counts file will have the count of cells under the `Count_IdentifyPrimaryObjects` column.
